[package]
name = "vku"
version = "0.1.0"
edition = "2021"
authors = ["Maximillian Pfeil <pfeil.maximillian@gmail.com>"]
description = "Utility crate for kickstarting vulkan development"
repository = "https://github.com/ArrowMaxGithub/vku"
license = "MIT OR Apache-2.0"
keywords = ["vku", "vulkan", "ash", "vma", "shaderc"]
categories = ["api-bindings", "graphics", "rendering"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = {version = "0.37.0", default-features = false, features = ["linked"]}
ash-window = "0.12.0"
raw-window-handle = "0.5.0"
vk-mem-alloc = "0.1.1"
shaderc = "0.8.0"
env_logger = {version = "0.9.0", features = ["termcolor", "humantime"]}
log = { version = "0.4.17"}
thiserror = "1.0.40"

[dev-dependencies]
winit = "0.28.3"
egui = "0.21.0"
egui-winit = "0.21.1"
anyhow = "1.0.70"
nalgebra-glm = "0.18.0"
image = "0.24.5"

[build-dependencies]
copy_to_output = "2.1.0"