[package]
name = "vku"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = {version = "0.37.0", default-features = false, features = ["linked"]}
ash-window = "0.12.0"
raw-window-handle = "0.5.0"
vk-mem-alloc = "0.1.1"
shaderc = "0.8.0"
spirv-reflect = "0.2.3"
env_logger = {version = "0.9.0", features = ["termcolor", "humantime"]}
log = { version = "0.4.17"}
anyhow = { version = "1.0", features = ["backtrace"] }
derive-error = "0.0.5"

[dev-dependencies]
winit = "0.27.5"